version: "3.9"

services:
  server:
    build: .
    command: python3.11 manage.py runserver 0.0.0.0:8002
    volumes:
      - ./reductionmedia:/reductionmedia/
      - ./martmp:/martmp/
      - ./marServer:/MAR/marServer/
    ports:
      - 8002:8002
  #  depends_on:
  #    - db
    extra_hosts:
     - "host.docker.internal:172.17.0.1"
    environment:
     - PYTHONUNBUFFERED=1
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
    
  
  frontend:
    build:
      context: ./MAR-frontend
    volumes:
      - react_build:/MAR-frontend/build
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  nginx:
    image: nginx:latest
    ports:
      - 3001:3001
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reductionmedia:/reductionmedia/
      - react_build:/var/www/react
    depends_on:
      - server
      - frontend

volumes:
  postgres_data:
  react_build:
