# Generated by Django 4.0.4 on 2022-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.DateField(auto_now_add=True)),
                ('logPath', models.CharField(max_length=250)),
                ('operation', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
