# Generated by Django 4.0.6 on 2022-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scibyfilter',
            name='finaltiles',
            field=models.ManyToManyField(related_name='final', to='files.finaltiles'),
        ),
    ]
