# Generated by Django 4.0.6 on 2022-09-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_scibyfilter_finaltiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockStartDate', models.DateField()),
                ('blockEndDate', models.DateField()),
                ('superFlatPath', models.CharField(max_length=250, null=True)),
                ('superFlatThumb', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('isvalid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scibyfilter',
            name='superFlatPath',
        ),
        migrations.RemoveField(
            model_name='scibyfilter',
            name='superFlatThumb',
        ),
        migrations.AddField(
            model_name='scibyfilter',
            name='superflat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files.superflat'),
        ),
    ]
