# Generated by Django 4.0.6 on 2022-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_superflat_remove_scibyfilter_superflatpath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superflat',
            name='files',
            field=models.TextField(null=True),
        ),
    ]
