# Generated by Django 4.0.6 on 2022-09-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_superflat_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scibyfilter',
            name='superflat',
        ),
        migrations.AddField(
            model_name='individualfile',
            name='superflat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files.superflat'),
        ),
    ]
