# Generated by Django 4.0.6 on 2022-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_scibyfilter_superflat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedsci',
            name='superFlatFile',
        ),
        migrations.RemoveField(
            model_name='processedsci',
            name='superFlatThumb',
        ),
    ]
