# Generated by Django 4.1.3 on 2023-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_fieldimages_finaltiles_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='finaltiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualfile',
            name='processedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
