# Generated by Django 4.1.3 on 2023-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_fieldimages_updated_at_file_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldimages',
            name='field',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
