# Generated by Django 4.1.3 on 2023-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_fieldimages_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
