# Generated by Django 4.1.3 on 2023-05-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_currentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualfile',
            name='raw_sci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='raw', to='files.individualfile'),
        ),
    ]
