# Generated by Django 4.1.3 on 2023-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_individualfile_raw_sci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scibyfilter',
            name='blockEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scibyfilter',
            name='blockStartDate',
            field=models.DateField(null=True),
        ),
    ]
