# Generated by Django 4.1.3 on 2023-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_scibyfilter_blockenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superflat',
            name='band',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
