# Generated by Django 4.1.3 on 2023-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_superflat_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciblock',
            name='blockEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sciblock',
            name='blockStartDate',
            field=models.DateField(null=True),
        ),
    ]
