# Generated by Django 4.1.3 on 2023-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_sciblock_blockenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superflat',
            name='blockEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='superflat',
            name='blockStartDate',
            field=models.DateField(null=True),
        ),
    ]
