# Generated by Django 4.1.3 on 2023-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_alter_superflat_blockenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualfile',
            name='isvalid',
            field=models.IntegerField(default=1),
        ),
    ]
