# Generated by Django 4.1.3 on 2023-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_individualfile_isvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualfile',
            name='moonmean',
            field=models.FloatField(null=True),
        ),
    ]
