# Generated by Django 4.1.3 on 2023-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_individualfile_moonmean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualfile',
            name='band',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
