# Generated by Django 4.1.3 on 2023-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_alter_individualfile_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualfile',
            name='crval1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='individualfile',
            name='crval2',
            field=models.FloatField(null=True),
        ),
    ]
