# Generated by Django 4.1.3 on 2023-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_individualfile_crval1_individualfile_crval2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30, unique=True)),
                ('locked_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
