# Generated by Django 4.1.3 on 2023-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_lockedfields_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroCatalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refname', models.CharField(max_length=30, null=True)),
                ('field', models.CharField(max_length=30, null=True)),
                ('file_path', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
